examples/DancingGoat/Controllers/DancingGoatProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using CMS.ContentEngine;
using CMS.Websites;

using DancingGoat;
using DancingGoat.Controllers;
using DancingGoat.Models;

using Kentico.Content.Web.Mvc;
using Kentico.Content.Web.Mvc.Routing;

using Microsoft.AspNetCore.Mvc;

[assembly: RegisterWebPageRoute(ProductsSection.CONTENT_TYPE_NAME, typeof(DancingGoatProductController), WebsiteChannelNames = new[] { DancingGoatConstants.WEBSITE_CHANNEL_NAME })]

namespace DancingGoat.Controllers
{
    public class DancingGoatProductController : Controller
    {
        private readonly ProductSectionRepository productSectionRepository;
        private readonly ProductPageRepository productPageRepository;
        private readonly ProductRepository productRepository;
        private readonly ITaxonomyRetriever taxonomyRetriever;
        private readonly IWebPageUrlRetriever urlRetriever;
        private readonly IWebPageDataContextRetriever webPageDataContextRetriever;
        private readonly IPreferredLanguageRetriever currentLanguageRetriever;


        public DancingGoatProductController(
            ProductSectionRepository productSectionRepository,
            ProductPageRepository productPageRepository,
            ProductRepository productRepository,
            IWebPageUrlRetriever urlRetriever,
            IPreferredLanguageRetriever currentLanguageRetriever,
            IWebPageDataContextRetriever webPageDataContextRetriever,
            ITaxonomyRetriever taxonomyRetriever)
        {
            this.productSectionRepository = productSectionRepository;
            this.productPageRepository = productPageRepository;
            this.productRepository = productRepository;
            this.urlRetriever = urlRetriever;
            this.webPageDataContextRetriever = webPageDataContextRetriever;
            this.currentLanguageRetriever = currentLanguageRetriever;
            this.taxonomyRetriever = taxonomyRetriever;
        }


        public async Task<IActionResult> Index()
        {
            var languageName = currentLanguageRetriever.Get();
            var webPage = webPageDataContextRetriever.Retrieve().WebPage;
            var productsSection = await productSectionRepository.GetProductsSection(webPage.WebPageItemID, languageName, HttpContext.RequestAborted);

            var products = await GetProducts(languageName, productsSection);

            var taxonomies = new Dictionary<string, TaxonomyViewModel>();
            var taxonomyNames = new List<string> { "CoffeeProcessing", "CoffeeTastes", "GrinderManufacturer", "GrinderType" };
            foreach (var taxonomyName in taxonomyNames)
            {
                var taxonomy = await taxonomyRetriever.RetrieveTaxonomy(taxonomyName, languageName);
                if (taxonomy.Tags.Any())
                {
                    taxonomies.Add(taxonomyName, TaxonomyViewModel.GetViewModel(taxonomy));
                }
            }

            var listModel = new ProductListViewModel(products, taxonomies);

            return View(listModel);
        }


        [HttpPost($"{{{WebPageRoutingOptions.LANGUAGE_ROUTE_VALUE_KEY}}}/{{controller}}/{{action}}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Filter(IDictionary<string, TaxonomyViewModel> filter)
        {
            var languageName = currentLanguageRetriever.Get();
            var webPage = webPageDataContextRetriever.Retrieve().WebPage;
            var productsSection = await productSectionRepository.GetProductsSection(webPage.WebPageItemID, languageName, HttpContext.RequestAborted);

            var products = await GetProducts(languageName, productsSection, filter);
            return PartialView("ProductsList", products);
        }


        private async Task<IEnumerable<ProductListItemViewModel>> GetProducts(string languageName, ProductsSection productsSection, IDictionary<string, TaxonomyViewModel> filter = null)
        {
            var products = await productRepository.GetProducts(languageName, filter ?? new Dictionary<string, TaxonomyViewModel>(), cancellationToken: HttpContext.RequestAborted);
            var productPages = await productPageRepository.GetProducts(productsSection.SystemFields.WebPageItemTreePath, languageName, products, cancellationToken: HttpContext.RequestAborted);

            return productPages.Select(productPage => ProductListItemViewModel.GetViewModel(productPage, urlRetriever, languageName).Result);
        }
    }
}

examples/DancingGoat/Views/DancingGoatProduct/Filter.cshtml
@using DancingGoat.Models

@model Dictionary<string, TaxonomyViewModel>

<form asp-controller="DancingGoatProduct" asp-action="Filter" autocomplete="off">
    @Html.Kentico().PageData()

    @foreach (var key in Model.Keys)
    {
        <h4>@HtmlLocalizer[Model[key].Name]</h4>
        @Html.HiddenFor(m => Model[key].Name)
        @Html.HiddenFor(m => Model[key].CodeName)
        @Html.EditorFor(model => model[key].Tags)
    }
</form>

examples/DancingGoat/Views/DancingGoatProduct/Index.cshtml
@using DancingGoat.Models

@model ProductListViewModel

@{
    ViewData["PageClass"] = "inverted";
}

<div class="product-page-container">
    <div class="product-page row">
        <div class="flex">
            <aside class="col-md-4 col-lg-3 product-filter">
                <partial name="Filter" model="@Model.Filter" />
            </aside>

            <div id="product-list" class="col-md-8 col-lg-9 product-list">
                <partial name="ProductsList" model="Model.Items" />
            </div>
        </div>
    </div>
</div>

    <script src="~/Scripts/formAutoPost.js"></script>

    <script>
        formAutoPost({ targetContainerSelector: "#product-list" });
    </script>

examples/DancingGoat/Views/DancingGoatProduct/ProductsList.cshtml
@using DancingGoat.Models

@model IEnumerable<ProductListItemViewModel>

@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 3 products on row for large screen -->
        <div class="col-md-6 col-lg-4">
            @Html.DisplayFor(m => product, "ProductListItem")
        </div>
    }
}
else
{
    <span class="ContentLabel">@HtmlLocalizer["No matching products."]</span>
}