examples/DancingGoat/Controllers/DancingGoatPrivacyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using CMS.ContactManagement;
using CMS.DataEngine;
using CMS.DataProtection;

using DancingGoat;
using DancingGoat.Controllers;
using DancingGoat.Helpers.Generator;
using DancingGoat.Models;

using Kentico.Content.Web.Mvc;
using Kentico.Content.Web.Mvc.Routing;

using Microsoft.AspNetCore.Mvc;

[assembly: RegisterWebPageRoute(PrivacyPage.CONTENT_TYPE_NAME, typeof(DancingGoatPrivacyController), WebsiteChannelNames = new[] { DancingGoatConstants.WEBSITE_CHANNEL_NAME })]

namespace DancingGoat.Controllers
{
    public class DancingGoatPrivacyController : Controller
    {
        private const string SUCCESS_RESULT = "success";
        private const string ERROR_RESULT = "error";

        private readonly IConsentAgreementService consentAgreementService;
        private readonly IInfoProvider<ConsentInfo> consentInfoProvider;
        private readonly IPreferredLanguageRetriever currentLanguageRetriever;
        private readonly IWebPageDataContextRetriever webPageDataContextRetriever;
        private readonly PrivacyPageRepository privacyPageRepository;
        private ContactInfo currentContact;


        private ContactInfo CurrentContact
        {
            get
            {
                if (currentContact == null)
                {
                    currentContact = ContactManagementContext.CurrentContact;
                }

                return currentContact;
            }
        }


        public DancingGoatPrivacyController(PrivacyPageRepository privacyPageRepository, IConsentAgreementService consentAgreementService, IInfoProvider<ConsentInfo> consentInfoProvider, IPreferredLanguageRetriever currentLanguageRetriever, IWebPageDataContextRetriever webPageDataContextRetriever)
        {
            this.privacyPageRepository = privacyPageRepository;
            this.consentAgreementService = consentAgreementService;
            this.consentInfoProvider = consentInfoProvider;
            this.currentLanguageRetriever = currentLanguageRetriever;
            this.webPageDataContextRetriever = webPageDataContextRetriever;
        }


        public async Task<IActionResult> Index()
        {
            var webPage = webPageDataContextRetriever.Retrieve().WebPage;

            var privacyPage = await privacyPageRepository.GetPrivacyPage(webPage.WebPageItemID, webPage.LanguageName, HttpContext.RequestAborted);

            var model = new PrivacyViewModel { WebPage = privacyPage };

            if (!IsDemoEnabled())
            {
                model.DemoDisabled = true;
            }
            else if (CurrentContact != null)
            {
                model.Consents = GetAgreedConsentsForCurrentContact();
            }

            model.ShowSavedMessage = TempData[SUCCESS_RESULT] != null;
            model.ShowErrorMessage = TempData[ERROR_RESULT] != null;
            model.PrivacyPageUrl = HttpContext.Request.Path;

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Revoke")]
        public ActionResult Revoke(string returnUrl, string consentName)
        {
            var consentToRevoke = consentInfoProvider.Get(consentName);

            if (consentToRevoke != null && CurrentContact != null)
            {
                consentAgreementService.Revoke(CurrentContact, consentToRevoke);

                TempData[SUCCESS_RESULT] = true;
            }
            else
            {
                TempData[ERROR_RESULT] = true;
            }

            return Redirect(returnUrl);
        }


        private IEnumerable<PrivacyConsentViewModel> GetAgreedConsentsForCurrentContact()
        {
            return consentAgreementService.GetAgreedConsents(CurrentContact)
                .Select(consent => new PrivacyConsentViewModel
                {
                    Name = consent.Name,
                    Title = consent.DisplayName,
                    Text = consent.GetConsentText(currentLanguageRetriever.Get()).ShortText
                });
        }


        private bool IsDemoEnabled()
        {
            return consentInfoProvider.Get(TrackingConsentGenerator.CONSENT_NAME) != null;
        }
    }
}

examples/DancingGoat/Views/DancingGoatPrivacy/Index.cshtml
@model DancingGoat.Models.PrivacyViewModel

@{
    ViewData["PageClass"] = "inverted no-bg";
}

<div class="container">
    @if (Model.DemoDisabled)
    {
        <text>
            <h2>@HtmlLocalizer["Data protection (GDPR) demo must be enabled."]</h2>
            <span>
                @HtmlLocalizer["You can enable data protection demo data in the administration interface (Configuration -> Sample data generator)."]
            </span>
        </text>
    }
    else
    {
        <h2>@HtmlLocalizer["Your agreed consents"]</h2>

        if (Model.ShowSavedMessage)
        {
            <span class="info-label">@HtmlLocalizer["Consent revocation was successful."]</span>
        }
        else if (Model.ShowErrorMessage)
        {
            <span class="error-label">@HtmlLocalizer["Consent revocation was not successful."]</span>
        }

        if (Model.Consents.Any())
        {
            var routeData = new Dictionary<string, string> { { "returnUrl", Model.PrivacyPageUrl } };
            <form asp-controller="DancingGoatPrivacy" asp-action="Revoke" asp-all-route-data="routeData" asp-antiforgery="true" method="post">
                @foreach (var consent in Model.Consents)
                {
                    <div class="consent-item">
                        <div class="row">
                            <div class="col-md-10">
                                <h3 class="consent-heading">@consent.Title</h3>
                            </div>
                            <div class="col-md-2">
                                <button type="submit" name="consentName" value="@consent.Name" class="btn btn-primary">@HtmlLocalizer["Revoke"]</button>
                            </div>
                        </div>
                        <div class="row">
                            <p>@Html.Raw(@consent.Text)</p>
                        </div>
                    </div>
                }
            </form>
        }
        else
        {
            <span>@HtmlLocalizer["There are currently no consents agreed by you."]</span>
        }
    }
</div>